# if SHORT over LONG
# it is an UPTREND
# if SHORT under LONG
# it is DOWNTREND
EMA_short = 28
EMA_long = 55

# RSI will determine a buy when it crosses back above the minimum threshold
# RSI will determine a sell when it crosses back down from above the max threshold

RSI_HIGH = 70
RSI_LOW = 30

# RSI interval
interval = 14
